import { Inter,Lemon,Rubik_Glitch,Chewy } from 'next/font/google'
import './globals.css'
import {hurricane, inter} from "@/fonts/fonts";

/*const inter = Inter({ subsets: ['latin'] })
const lemon = Lemon({ weight: '400',subsets:['latin'] })
const rubik_rlitch = Rubik_Glitch({ weight: '400',subsets:['latin'] })*/
const chewy = Chewy({ weight: '400',subsets:['latin'] })
export const metadata = {
  title: 'rukon.pro->home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={chewy.className}>{children}</body>
    </html>
  )
}
