import './globals.css'
import {chewy} from "@/app/utils/fonts/fonts";

export const metadata = {
  title: 'rukon.pro->home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={chewy.className}>
      {children}
      </body>
    </html>
  )
}
